apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-service-data
  labels:
    app: tts-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
